io-func-sign-issuer:
  - '\(issuer\)'
  - '\(io-func-sign-issuer\)'
io-func-sign-user:
  - '\(user\)'
  - '\(io-func-sign-user\)'
internal:
  - '\(internal\)'
  - '\(package\)'
  - '\(io-sign\)'
  - '\(io-services\)'
  - '\(pdv-tokenizer\)'
docs:
  - "^docs"
# fix:
#   - "^fix"
chore:
  - "^chore"
feat:
  - "^feat"
build:
  - "^build"
ci:
  - "^ci"
refactor:
  - "^refactor"
breaking:
  - ":!"
