changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Chore
      labels:
        - chore
    - title: Breaking Changes
      labels:
        - breaking
    - title: Exciting New Features
      labels:
        - feature
    - title: Fixes
      labels:
        - fix
    - title: Other Changes
      labels:
        - "*"
