openapi: 3.0.3
info:
  title: IO Sign - User API
  version: 0.0.1
security:
  - FunctionsKey: []
paths:
  /signers:
    post:
      operationId: getSignerByFiscalCode
      tags:
        - Signer
      summary: Get Signer By Fiscal Code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetSignerByFiscalCodeBody"
      responses:
        "201":
          description: The Signer detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignerDetailView"
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        default:
          $ref: "#/components/responses/Unexpected"

components:
  securitySchemes:
    FunctionsKey:
      type: apiKey
      name: X-Functions-Key
      in: header

  responses:
    NotFound:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/responses/NotFound"
    BadRequest:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/responses/BadRequest"
    Forbidden:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/responses/Forbidden"
    Unexpected:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/responses/Unexpected"
  schemas:
    Id:
      type: string
      description: Entity Id
      format: ulid
      example: 01ARZ3NDEKTSV4RRFFQ69G5FAV
    Timestamp:
      type: string
      format: UTCISODateFromString
      description: A date-time field in ISO-8601 format and UTC timezone.
      x-import: "@pagopa/ts-commons/lib/dates"
      example: "2018-10-13T00:00:00.000Z"

    GetSignerByFiscalCodeBody:
      type: object
      properties:
        fiscal_code:
          $ref: "#/components/schemas/FiscalCode"
      required:
        - fiscal_code

    SignerDetailView:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Id"
      required:
        - id

    FiscalCode:
      type: string
      description: User's fiscal code.
      format: FiscalCode
      x-import: "@pagopa/ts-commons/lib/strings"
      example: SPNDNL80R13C555X
